config/routes.rb
Rails.application.routes.draw do
  resources :homes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: %i[ show edit update destroy ]

  # GET /homes or /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1 or /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes or /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: "Home was successfully created." }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1 or /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: "Home was successfully updated." }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1 or /homes/1.json
  def destroy
    @home.destroy!

    respond_to do |format|
      format.html { redirect_to homes_path, status: :see_other, notice: "Home was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def home_params
      params.fetch(:home, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_with(model: home) do |form| %>
  <% if home.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
        <% home.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/_home.html.erb
<div id="<%= dom_id home %>">
</div>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render "form", home: @home %>

<br>

<div>
  <%= link_to "Show this home", @home %> |
  <%= link_to "Back to homes", homes_path %>
</div>

app/views/homes/index.html.erb
<div class="main-page text-white " style="padding-top: 7rem; ">
  <div class="row container mx-auto p-4 justify-content-between">
    <div class="col-12 col-md-6 col-lg-7">
      <h2 class="fw-bold">Bring home beautiful interiors that fit your budget</h2>
      <p>
        Experience unmatched quality & timely delivery with Livspace
      </p>
    </div>
    <div class="col-12 col-md-6 col-lg-4">
      <form class="p-4 rounded bg-white text-dark shadow">
        <h3>Let's Connect</h3>
        <p>Tell us some basic information, and Our executive will get back to you.
        </p>
        <div class="mb-1">
          <label for="exampleInputEmail1" class="form-label">Email address</label>
          <input type="email" class="form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-1">
          <label for="exampleInputName" class="form-label">Full Name</label>
          <input type="text" class="form-control form-control-sm" id="exampleInputName" aria-describedby="emailHelp">
        </div>
        <div class="mb-2">
          <label for="exampleInputContact" class="form-label">Contact Number</label>
          <input type="number" class="form-control form-control-sm" id="exampleInputContact" aria-describedby="emailHelp">
        </div>
  
        <div class="input-group mb-2">
          <label class="input-group-text" for="inputGroupSelect02" style="line-height: 0.5rem;">Select State</label>
          <select class="form-select form-select-sm" id="inputGroupSelect02" >
            <option selected>Choose...</option>
            <option value="1">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
          </select>   
        </div>

        <div class="input-group mb-2">
          <label class="input-group-text" for="inputGroupSelect02" style="line-height: 0.5rem;">Select City</label>
          <select class="form-select form-select-sm" id="inputGroupSelect02">
            <option selected>Choose...</option>
            <option value="1">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
          </select>   
        </div>

        <div class="text-center mt-1 d-grid">
          <button type="submit" class="btn  btn-custom">Submit</button>
        </div>     
      </form>
    </div>
  </div>
</div>
<!--about -->
<div class="container my-5">
  <div class="about-content p-2 ">
    <h2 class="text-center my-4">
      Why Choose us
    </h2>
    <hr class="mx-auto" style="width: 60px; height: 4px; background-color: #541eaa; border: 0;">

    <p>
      When you give your home the Livspace touch, you get both beauty and functionality. We employ state-of-the-art technology to ensure your home features a flawless look that lasts a very long time.
      When you give your home the Livspace touch, you get both beauty and functionality. We employ state-of-the-art technology to ensure your home features a flawless look that lasts a very long time.
      When you give your home the Livspace touch, you get both beauty and functionality. We employ state-of-the-art technology to ensure your home features a flawless look that lasts a very long time.
    </p>
  </div>
</div>
<!--caousel section-->
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 col-lg-6 text-dark d-flex align-items-center ">
      <div class="content">
        <h2 class="my-3">
          The home design you crave
        </h2>
        <hr class="" style="width: 100px; height: 4px; background-color: #541eaa; border: 0;">
        <p>
          When you give your home the Livspace touch, you get both beauty and functionality. We employ state-of-the-art technology to ensure your home features a flawless look that lasts a very long time.
        </p>
      </div>
    </div>
    <div class="col-12 col-md-6 col-lg-6">
      <div class="rotation-container">
        <div class="item-container item-container-1">
          <a href="#" class="item text-center text-decoration-none item-1">
            <lord-icon
            src="https://cdn.lordicon.com/jdgfsfzr.json"
            trigger="hover"
            colors="primary:#121331,secondary:#ffffff" class="icon-styling"
           ></lord-icon>100% Quality Assurance
          </a>
        </div>
        <div class="item-container item-container-2">
          <a href="#" class="item text-center text-decoration-none item-2">
            <lord-icon
            src="https://cdn.lordicon.com/jdgfsfzr.json"
            trigger="hover"
            colors="primary:#121331,secondary:#ffffff" class="icon-styling"
           ></lord-icon>Personalised designs
          </a>
        </div>
        <div class="item-container item-container-3">
          <a href="#" class="item text-center text-decoration-none item-3">
            <lord-icon
            src="https://cdn.lordicon.com/jdgfsfzr.json"
            trigger="hover"
            colors="primary:#121331,secondary:#ffffff" class="icon-styling"
           ></lord-icon>Transparent pricing
          </a>
        </div>
        <div class="item-container item-container-4">
          <a href="#" class="item text-center text-decoration-none item-4">
            <lord-icon
            src="https://cdn.lordicon.com/jdgfsfzr.json"
            trigger="hover"
            colors="primary:#121331,secondary:#ffffff" class="icon-styling"
           ></lord-icon>Dedicated Support Team
          </a>
        </div>
        <div class="item-container item-container-5">
          <a href="#" class="item text-center text-decoration-none item-5">
            <lord-icon
            src="https://cdn.lordicon.com/jdgfsfzr.json"
            trigger="hover"
            colors="primary:#121331,secondary:#ffffff" class="icon-styling"
           ></lord-icon>Durable Modular Furniture
          </a>
        </div>
        <div class="item-container item-container-6">
          <a href="#" class="item text-center text-decoration-none item-6">
            <lord-icon
            src="https://cdn.lordicon.com/jdgfsfzr.json"
            trigger="hover"
            colors="primary:#121331,secondary:#ffffff" class="icon-styling"
           ></lord-icon>Dedicated Support Team
          </a>
        </div>  
    </div>
    </div>
  </div>
</div>

<!--caousel new section-->
<style>

/* Reseteo básico */
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
  /*outline: solid 1px red;*/
}

/* Estilos generales */

/* Bento Grid */
.grid-item {
  background-color: #f5e8ff;
  padding-block-end: 2.5rem;
  text-align: center;
  display: grid;
  justify-content: center;
  padding-top: 2rem;
  position: relative;
}

/* Estilo del contenedor del carrusel */
.carousel-container {
  width: 100%;
  padding: 3rem;
  overflow: hidden;
  display: flex;
  justify-content: center;
  align-items: center;
}

/* Contenido del carrusel */
.carousel-content {
  display: flex;
  animation: scroll 50s linear infinite;
}

/* Cada elemento del carrusel */
.carousel-item {
  min-width: 200px;
  height: 150px;
  margin-right: 10px;
  display: flex;
  justify-content: center;
  align-items: center;
}

.carousel-item img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  border-radius: 8px;
}

/* Animación para el scroll automático */
@keyframes scroll {
  0% {
    transform: translateX(0);
  }
  100% {
    transform: translateX(-50%);
  }
}

section {
  display: flex;
  width: 100%;
  height: 100%;
  max-width: 100%;
  max-height: 100%;
  place-items: center;
  margin: 0px;
  padding: 0px;
  list-style-type: none;
  opacity: 1;
  mask-image: linear-gradient(
    to right,
    rgba(0, 0, 0, 0) 0%,
    rgb(0, 0, 0) 12.5%,
    rgb(0, 0, 0) 87.5%,
    rgba(0, 0, 0, 0) 100%
  );
  overflow: hidden;
}
</style>

<div class="grid-item" id="projects">
  <h2>Transforming Your Space</h2>
  <hr class="mx-auto" style="width: 60px; height: 4px; background-color: #541eaa; border: 0;">
  <p>Look no further than Ishana Interior for end-to-end interior design services
  </p>
  <div class="carousel-container">
    <section>
      <ul>
        <div class="carousel-content">
          <div class="carousel-item"><%= image_tag 'A1.png' %></div>
          <div class="carousel-item"><%= image_tag 'A2.png' %></div>
          <div class="carousel-item"><%= image_tag 'A3.png' %></div>
          <div class="carousel-item"><%= image_tag 'V1.png' %></div>
          <div class="carousel-item"><%= image_tag 'A1.png' %></div>
          <div class="carousel-item"><%= image_tag 'V3.png' %></div>
          <div class="carousel-item"><%= image_tag 'A1.png' %></div>
          <div class="carousel-item"><%= image_tag 'A2.png' %></div>
          <div class="carousel-item"><%= image_tag 'A3.png' %></div>
          <div class="carousel-item"><%= image_tag 'V1.png' %></div>
          <div class="carousel-item"><%= image_tag 'A1.png' %></div>
          <div class="carousel-item"><%= image_tag 'V3.png' %></div>
          <div class="carousel-item"><%= image_tag 'A1.png' %></div>
          <div class="carousel-item"><%= image_tag 'A2.png' %></div>
          <div class="carousel-item"><%= image_tag 'A3.png' %></div>
          <div class="carousel-item"><%= image_tag 'V1.png' %></div>
          <div class="carousel-item"><%= image_tag 'A1.png' %></div>
          <div class="carousel-item"><%= image_tag 'V3.png' %></div>
        </div>
      </ul>
    </section>
  </div>
</div>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render "form", home: @home %>

<br>

<div>
  <%= link_to "Back to homes", homes_path %>
</div>

app/views/homes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @home %>

<div>
  <%= link_to "Edit this home", edit_home_path(@home) %> |
  <%= link_to "Back to homes", homes_path %>

  <%= button_to "Destroy this home", @home, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IshanaProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" href="<%= asset_path('logo.jpg') %>" type="image/x-icon">



    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.lordicon.com/lordicon.js"></script>


  </head>

  <body>
  <div class="main-div">
    <%= render 'shared/header' %>
    
      <%= yield %>
    </div>
   
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="container-fluid navbar navbar-expand-lg navbar-white bg-white fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">
      <%= image_tag 'logo.jpg', style: 'height: 2rem; width: auto; margin-right: 1rem;' %>
      Ishana Interio
    </a>
    <button type="button" class="btn btn-custom btn-sm">Book an Appointment</button>
  </div>
</nav>